version: "3.8"

networks:
  app-tier:
    driver: bridge
services:
  app:
    networks:
      - app-tier
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    environment:
      NODE_ENV: development
    ports:
      - 8080:3000
      # debugging port
      - 9229:9229
    volumes:
      - .:/towchores/src/app
      - ./towchores/src/app/node_modules
    links:
      - mysql
    depends_on:
      - mysql
    command: npm run start:docker-dev-debug

  mysql:
    networks:
      - app-tier
    image: mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --innodb_ft_min_token_size=2
    volumes:
      - ./dev-mariadb/data:/var/lib/mysql #docker container가 중지되더라도 db의 데이터가 날아가지 않도록 원하는 디렉토리에 볼륨매핑을 설정한다.
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306

